language: php

php:
  - 7.2
  - 7.3
  - 7.4snapshot
  - nightly

env:
  global:
    - REPORT_EXIT_STATUS=1
  matrix:
    - ENABLE_OPCACHE=1
    - ENABLE_OPCACHE=0

matrix:
  allow_failures:
    - php: nightly
      env: ENABLE_OPCACHE=0
    - php: nightly
      env: ENABLE_OPCACHE=1

before_install:
  - sudo apt-get update
  - sudo apt-get install -y libmpdec-dev
  - phpenv config-rm xdebug.ini || true

install:
    - phpize
    - ./configure
    - make -j
    - make install

before_script:
  - echo "extension=decimal.so"               >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "opcache.enable_cli=$ENABLE_OPCACHE" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

script:
  - wget -q -O run-tests.php https://raw.githubusercontent.com/php/php-src/master/run-tests.php
  - php run-tests.php -P -q -g FAIL,XFAIL,SKIP,BORK,WARN,LEAK,REDIRECT --show-diff
